### ISSUE TITLE
Initial mock-up

### ISSUE THREAD

**Issue by sangwon-hyun** [robohyun66/flowcy-shiny#3]
Initial mock-up for the shiny app design.

**Comment by sangwon-hyun** [comment]
[shiny flowcy.pdf](https://github.com/robohyun66/flowcy-shiny/files/4899958/shiny.flowcy.pdf)
@QinHE325 @jacobbien  Please provide any comments or ask if anything is unclear. The second page has an "easier version" of the mockup that I think we can start with.

**Comment by jacobbien** [comment]
Looks great!
