### ISSUE TITLE
Plot the 3 scatter plots with animation 

### ISSUE THREAD

**Issue by QinHE325** [robohyun66/flowcy-shiny#6]
Try to generate the 3 scatter plots shown at the top of mock up with animation using "plotly" package.

**Comment by sangwon-hyun** [comment]
Calling the three scatter plots 1,2, and 3, also add a plot with a covariate (plot 4), positioned like this:
123
444
where the covariates are a constant time series plot over time (multiple lines, one for each covariate), and the only thing moving is a vertical line at the time point.
